import type { Metadata } from "next";
import "./globals.css";
import MainNavigation from "@/components/header/MainNavigation";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body>
          <MainNavigation />
          <div className="max-w-4xl mx-auto mt-6">{children}</div>
          {/* {children} */}
        </body>
      </html>
    </ClerkProvider>
  );
}
